@startuml gochat-server-uml
package Server {
    frame main {
        [signalHandler]
        [handlePush]
        [handleConn]
        frame sendTo {
            [send packet]
            [push notify]
            [forward message]
        }
        [recvFrom] as recvFrom
    }
    frame poster
    frame push
    frame storage {
        database sqlite {
            [Account]
            [Message]
        }
    }
    frame auth

    folder biz {
        [base]
        [signup]
        [signin]
        [val-token]
        [users]
        [recv-msg]
        [ping]
        [signout]
    }
}
signup .up.> base
signin .up.> base
[val-token] .up.> base
users .up.> base
[recv-msg] .up.> base
ping .up.> base
signout .up.> base

[val-token] -up-> auth : parse/generate token
signup -up-> auth : generate token
signin -up-> auth : generate token

base -up-> poster : send packet to client
base -up-> push : push notify to client
base -up-> storage

recvFrom -up-> signup
recvFrom -up-> signin
recvFrom -up-> [val-token]
recvFrom -up-> users
recvFrom -up-> [recv-msg]
recvFrom -up-> ping
recvFrom -up-> signout

handleConn .up.> sendTo
handleConn .up.> recvFrom

poster ..> [send packet] : channel
push ..> handlePush : channel
handlePush .left.> [push notify] : channel
[forward message] -left-> storage
@enduml